# Generated by Django 4.2.16 on 2026-07-06 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('bandit', 'Bandit'), ('semgrep', 'Semgrep'), ('safety', 'Safety'), ('pylint', 'Pylint'), ('playwright', 'Playwright'), ('locust', 'Locust')], max_length=30)),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='URL Analizada')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.FloatField(default=0, help_text='Duración en segundos')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('success', 'Finalizado'), ('warning', 'Advertencia'), ('error', 'Error')], default='pending', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('findings', models.IntegerField(default=0)),
                ('recommendations', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escaneo',
                'verbose_name_plural': 'Escaneos',
                'ordering': ['-started_at'],
            },
        ),
    ]
